### ISSUE TITLE
element is not a function

### ISSUE THREAD

**Issue by rostgoat** [klamping/wdio-starter-kit#3]
following your instructions, I added functionality into `isLoggedIn`

```
class Login {
  get email () { return $('input[name="email"]'); }
  get password () { return $('input[name="password"]'); }
  get submit () { return $('button*=Sign in'); }
  get signUpLink () { return $('*=Sign Up'); }
  get clientLink () { return $('a*=Clients'); }

  login (email, password) {
    this.email.setValue(email);
    this.password.setValue(password);

    this.submit.click();
  }

  isLoggedIn () {
    this.clientLink.isDisplayed();
  }
}

module.exports = Login;
```

I keep getting `TypeError: this.clientLink.isDisplayed is not a function` when I run `npm test` 

why is this?

**Comment by klamping** [comment]
If you happened to upgrade the wdio package to v5, `isDisplayed` is no longer a function. Alternatively, the selector for `clientLink` isn't correct. Would need to know what your dependencies and test flow are.

**Comment by rostgoat** [comment]
you're right. I was running v5 stuff in v4 repo.

**Comment by klamping** [comment]
no worries. I need to update this repo to v5 sometime
